name: base
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12
  - pandas
  - requests
  - pyyaml
  - numpy
  - scikit-learn
  - jupyterlab
  - pylint
  - pytest
  - freezegun
  - pip
  - pip:
      - homeassistant
      - requests
      - setuptools
      - jwt
      - pydantic
      - aiohttp
      - freezegun
      - fastapi
