name: base
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.12  # Adjust this to your preferred Python version
  - pylint
  - pytest
  - freezegun
  - pip
  - pip:
      - homeassistant
      - requests
      - setuptools
      - jwt
      - pydantic
      - aiohttp
      - freezegun
