name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.12","3.13"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install pylint
          pip install jwt
          pip install pytz
          pip install dateutil
          pip install pydantic
          pip install setuptools
          pip install freezegun

      - name: Run Pylint with Configuration
        run: |
          pylint $(git ls-files '*.py') --rcfile=.pylintrc
